// Intelligent routing: maps issue_type + ward → department + officer
// This is a lookup table for MVP. Replace with live municipal API later.

export interface RoutingResult {
  department: string;
  officer: string;
  sla_hours: number;
}

const DEPARTMENT_MAP: Record<string, { department: string; officer: string; sla_hours: number }> = {
  "Road Damage / Pothole":          { department: "Public Works Department (PWD)", officer: "Jr. Engineer — Roads Division", sla_hours: 48 },
  "Garbage Dump":                    { department: "Solid Waste Management", officer: "Sanitation Inspector", sla_hours: 24 },
  "Drainage Issue / Water Logging":  { department: "Storm Water Drainage Dept.", officer: "Drainage Supervisor", sla_hours: 24 },
  "Streetlight Issue":               { department: "Electrical Maintenance", officer: "Electrical Inspector", sla_hours: 36 },
  "Water Leakage":                   { department: "Water Supply Department", officer: "Hydraulic Engineer", sla_hours: 12 },
  "Sewage Issue":                    { department: "Sewage & Sanitation Dept.", officer: "Sanitation Officer", sla_hours: 24 },
  "Road Debris / Construction Waste":{ department: "Public Works Department (PWD)", officer: "Site Inspector", sla_hours: 48 },
  "Other":                           { department: "General Complaints Cell", officer: "Ward Officer", sla_hours: 72 },
  // Legacy labels from older version
  "Pothole":                         { department: "Public Works Department (PWD)", officer: "Jr. Engineer — Roads Division", sla_hours: 48 },
  "Road Damage":                     { department: "Public Works Department (PWD)", officer: "Jr. Engineer — Roads Division", sla_hours: 48 },
  "Drainage Issue":                  { department: "Storm Water Drainage Dept.", officer: "Drainage Supervisor", sla_hours: 24 },
};

export function routeIssue(issueType: string, ward?: string | null): RoutingResult {
  const entry = DEPARTMENT_MAP[issueType] || DEPARTMENT_MAP["Other"];
  return {
    department: entry.department,
    officer: ward ? `${entry.officer} — ${ward}` : entry.officer,
    sla_hours: entry.sla_hours,
  };
}

// Severity auto-mapping from AI confidence + issue type
export function autoSeverity(issueType: string, confidence: number): "low" | "medium" | "high" | "critical" {
  const highSeverityTypes = ["Road Damage / Pothole", "Pothole", "Water Leakage", "Sewage Issue"];
  if (highSeverityTypes.includes(issueType) && confidence > 0.85) return "critical";
  if (highSeverityTypes.includes(issueType)) return "high";
  if (confidence > 0.9) return "high";
  if (confidence > 0.7) return "medium";
  return "low";
}

// Simple duplicate detection: compare description similarity + location + category
export function checkDuplicate(
  newIssue: { issue_type: string; ward?: string | null; locality?: string | null; description: string },
  existingIssues: { id: string; issue_type: string; ward?: string | null; locality?: string | null; description: string; status: string }[]
): string | null {
  // Only check non-resolved issues
  const active = existingIssues.filter(i => !["resolved", "rejected", "invalid"].includes(i.status));

  for (const existing of active) {
    // Same type + same ward/locality = potential duplicate
    if (existing.issue_type !== newIssue.issue_type) continue;

    const sameWard = existing.ward && newIssue.ward && existing.ward.toLowerCase() === newIssue.ward.toLowerCase();
    const sameLocality = existing.locality && newIssue.locality && existing.locality.toLowerCase() === newIssue.locality.toLowerCase();

    if (!sameWard && !sameLocality) continue;

    // Simple word overlap check (lightweight, no embeddings)
    const newWords = new Set(newIssue.description.toLowerCase().split(/\s+/).filter(w => w.length > 3));
    const existWords = new Set(existing.description.toLowerCase().split(/\s+/).filter(w => w.length > 3));
    let overlap = 0;
    for (const w of newWords) {
      if (existWords.has(w)) overlap++;
    }
    const similarity = newWords.size > 0 ? overlap / newWords.size : 0;

    if (similarity > 0.4) {
      return existing.id; // Return ID of the duplicate
    }
  }

  return null;
}

// Generate formal complaint text
export function generateComplaintText(data: {
  issue_type: string;
  locality?: string | null;
  ward?: string | null;
  description: string;
  priority: string;
  timestamp: string;
}): string {
  return `FORMAL CIVIC COMPLAINT REPORT
═══════════════════════════════════════
Issue Type: ${data.issue_type}
Priority: ${data.priority.toUpperCase()}
Location: ${data.locality || "Not specified"}${data.ward ? `, ${data.ward}` : ""}
Filed On: ${data.timestamp}
═══════════════════════════════════════

DESCRIPTION:
${data.description}

This report has been auto-generated by CivicPulse AI and verified by the citizen before submission. The assigned department is expected to acknowledge this within the SLA window.

— CivicPulse Automated Civic Intelligence`;
}
